name: CI

on:
  push:
    branches:
      - develop
      - main

jobs:
  docker-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build containers
        run: docker compose build

      - name: Start services
        run: docker compose up -d

      - name: Show status
        run: docker compose ps

      - name: Stop services
        run: docker compose down
